"""
attract_scorer.py — Score a generated story for channel audience fit + pipe gating.

One small Claude call reads the story title + body and returns a 0–100 score
plus a per-dimension breakdown. Works for both EN and ZH story text.

Optimizes for THIS channel's audience retention, not general news value.
Channel identity: "Hidden systems made visible."

Used by:
  - generate_story_batch() in generator.py (real-time, after each story save)
  - score_existing.py (retroactive, one-time calibration script)

Scoring dimensions (total 100):
  curiosity_gap             0–20
  ordinary_people_stakes    0–20
  hidden_mechanism          0–20
  consequence_clarity       0–15
  audience_fit              0–15
  title_retention_alignment 0–5
  low_context_accessibility 0–5
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)

_PROMPTS_DIR = Path(__file__).resolve().parent.parent / "prompts"
# __file__ = story_engine/src/engine/attract_scorer.py
# .parent        = story_engine/src/engine/
# .parent.parent = story_engine/src/
# → story_engine/src/prompts/  ✓


def _prompt_path(lang: str) -> Path:
    """
    Pick the attract-score prompt file for the given language.

    Routes:
        lang='en'  → attract_score_en.txt  (English-audience rubric)
        otherwise  → attract_score_zh.txt  (default / ZH rubric)

    Both files use identical dimensions and JSON schema, so downstream code
    (total computation, breakdown storage) is unchanged.
    """
    name = "attract_score_en.txt" if lang == "en" else "attract_score_zh.txt"
    return _PROMPTS_DIR / name

_CLAUDE_BIN = os.environ.get("CLAUDE_BIN", "claude")

_DIMS = [
    "curiosity_gap",
    "ordinary_people_stakes",
    "hidden_mechanism",
    "consequence_clarity",
    "audience_fit",
    "title_retention_alignment",
    "low_context_accessibility",
]

# Default max score per dimension (hardcoded rubric, sums to 100)
_DIMS_MAX: dict = {
    "curiosity_gap":             20,
    "ordinary_people_stakes":    20,
    "hidden_mechanism":          20,
    "consequence_clarity":       15,
    "audience_fit":              15,
    "title_retention_alignment":  5,
    "low_context_accessibility":  5,
}

# ── Change 4: Calibrated dimension weights ────────────────────────────────────
# attract_weights.json is auto-generated by scripts/calibrate_attract_weights.py
# and contains new max scores (summing to 100) derived from Pearson correlation
# of each dimension vs actual video performance.
# Fail-open: if absent or malformed, falls back to _DIMS_MAX (no behaviour change).
_CONFIG_DIR      = Path(__file__).resolve().parents[2] / "config"
_WEIGHTS_PATH    = _CONFIG_DIR / "attract_weights.json"
_PRED_ERR_PATH   = _CONFIG_DIR / "prediction_errors.json"

def _load_json_config(path: Path) -> dict:
    """Load a JSON config file; return {} on any error (fail-open)."""
    try:
        with open(path) as f:
            return json.load(f)
    except FileNotFoundError:
        return {}
    except Exception as e:
        logger.warning("attract_scorer: could not load %s — %s", path.name, e)
        return {}

_attract_weights:    dict = _load_json_config(_WEIGHTS_PATH)
_prediction_errors:  dict = _load_json_config(_PRED_ERR_PATH)

if _attract_weights:
    logger.info(
        "attract_scorer: loaded calibrated weights from %s (%d dims)",
        _WEIGHTS_PATH.name, len(_attract_weights),
    )
if _prediction_errors:
    logger.info(
        "attract_scorer: loaded prediction errors from %s (%d types)",
        _PRED_ERR_PATH.name, len(_prediction_errors),
    )


def score_story(title: str, body: str, lang: str = "zh") -> tuple[int | None, dict]:
    """
    Score a story on six attractiveness dimensions using Claude.

    Returns:
        (total_score, breakdown_dict)
        total_score: int 0–100 (deterministically summed from 6 dimension scores)
        breakdown_dict: {dimension: {"score": int, "reason": str}, ...}

    On any failure, returns (None, {}) — caller must check for None before saving.
    The gate in run_generate.sh treats NULL score as pass (fail open), so callers
    must NOT save a failure result to DB — only save when score is not None.
    """
    try:
        prompt_template = _prompt_path(lang).read_text(encoding="utf-8")
    except Exception as exc:
        logger.error("attract_scorer: cannot read prompt — %s", exc)
        return None, {}

    prompt = prompt_template.format(
        title=title,
        body=body[:3000],   # cap body to keep call cheap (~500 tokens input)
    )

    try:
        result = subprocess.run(
            [_CLAUDE_BIN, "--output-format", "text", "--max-turns", "1",
             "--tools", "", "-p", prompt],
            capture_output=True, text=True, timeout=45,
            cwd=Path(__file__).resolve().parents[2],   # story_engine/
        )
        raw = result.stdout.strip()
    except Exception as exc:
        logger.error("attract_scorer: Claude call failed — %s", exc)
        return None, {}

    # Strip markdown code fences if present
    if raw.startswith("```"):
        raw = "\n".join(raw.split("\n")[1:])
        raw = raw.rsplit("```", 1)[0].strip()

    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        logger.error("attract_scorer: invalid JSON response — %r", raw[:200])
        return None, {}

    # Guard: if the LLM returned valid JSON but scored fewer than 4 of 7 dimensions,
    # it likely failed silently (returned {}, nulls, or garbled output that still parsed).
    # Return None so the gate treats this as "no score" rather than saving a false 0.
    scored_dims = sum(1 for d in _DIMS if int((data.get(d) or {}).get("score", 0)) > 0)
    if scored_dims < 4:
        logger.error(
            "attract_scorer: only %d/%d dimensions scored — LLM response likely malformed "
            "(returning None to prevent false score=0 blocking a valid story)",
            scored_dims, len(_DIMS),
        )
        return None, {}

    # ── Change 4: Compute total with calibrated weights ───────────────────────
    # If attract_weights.json exists, each dimension's raw score (0–old_max) is
    # rescaled to 0–new_weight, giving calibrated importance based on observed
    # correlation with actual video retention + CTR.
    # Fallback: simple sum over _DIMS_MAX (original behaviour).
    if _attract_weights:
        weighted_total = 0.0
        for d in _DIMS:
            raw_score  = int((data.get(d) or {}).get("score", 0))
            old_max    = _DIMS_MAX.get(d, 1)
            new_weight = _attract_weights.get(d, old_max)
            weighted_total += raw_score * (new_weight / old_max) if old_max > 0 else raw_score
        total = max(0, min(100, round(weighted_total)))
    else:
        total = sum(int((data.get(d) or {}).get("score", 0)) for d in _DIMS)

    # ── Change 2: Apply prediction error correction ───────────────────────────
    # prediction_errors.json maps story_type → mean(actual_perf − predicted/100).
    # Correction is scaled ×10 to 0–100 space and clamped to ±1.5 points so
    # the gate thresholds are nudged, never overridden.
    # story_type is extracted from the LLM response (may be flat str or nested dict).
    story_type_raw = data.get("story_type")
    if isinstance(story_type_raw, dict):
        story_type = str(
            story_type_raw.get("value") or
            story_type_raw.get("type")  or
            "other"
        )
    elif isinstance(story_type_raw, str) and story_type_raw:
        story_type = story_type_raw
    else:
        story_type = "other"

    if _prediction_errors and story_type in _prediction_errors:
        correction = _prediction_errors[story_type]   # already clamped ±0.15 by script
        # ×10 → ±1.5 point adjustment in 0–100 space
        delta = round(correction * 10)
        if delta != 0:
            old_total = total
            total = max(0, min(100, total + delta))
            logger.debug(
                "attract_scorer: prediction error correction — type=%s delta=%+d "
                "score %d → %d",
                story_type, delta, old_total, total,
            )

    breakdown = {
        k: v for k, v in data.items()
        if k not in ("total", "verdict")
    }
    return total, breakdown
